### ISSUE TITLE
无自动复仇-自动转盘-自动开免费宝箱-自动进攻

### ISSUE THREAD

**Issue by leapsea** [seatom/crysadm#1]
虽然有这个设置，开了但是没用。除了自动收取正常工作，其他均未自动执行。（自动提现未测试）
安装环境：树莓派
运行命令 sudo sh run.sh
不知道有没有错误日志记录。

**Comment by seatom** [comment]
是存在一些bug，你要把自动提现打开，其他的自动任务才会执行，如果你不想提现，可以把提现的下限值设置大一点

发自我的手机

**Comment by leapsea** [comment]
thanks，尝试修改一下
