### ISSUE TITLE
进不去install界面

### ISSUE THREAD

**Issue by xuexiyong** [seatom/crysadm#4]
安装完 ip:4000/install  直接跳到登录界面了，应该怎么办？
我是安装别人的版本不好使，直接删除文件夹有安装您的版本
然后我看setup文件里面有个cron。sh  您的git文件里没有，
我在别人的那里下了一个这个放到目录里了
安装完毕还是跳不到名字和密码的界面

**Comment by seatom** [comment]
在删除crysadm 文件夹之后还应该删除redis数据库，sudo apt-get remove redis,然后再重新git clone 



发自我的手机

**Comment by xuexiyong** [comment]
感谢，解答！
我在输入 sodu apt-get remove redis 的时候提示我未发现软件包
是怎么回事，我的源是阿里的源

在 2016年6月5日 下午1:32，Seatom <notifications@github.com>写道：

**Comment by seatom** [comment]
��������sodu apt-get remove redis-server 



������������

> �� 2016��6��5����13:39��xuexiyong <notifications@github.com> ������
> 
> sodu apt-get remove redis

**Comment by xuexiyong** [comment]
试过这个命令了程序也重新安装了还是弹不出来
关于cron.sh这个文件 应该怎么处理？
您的脚本文件里面还有这个文件的安装

**Comment by seatom** [comment]
Cron .sh是一个定时任务，后来发现用处不大，就把它删掉了，这个可以不用管



发自我的手机

**Comment by xuexiyong** [comment]
感谢解答，没有linux基础，重新又安装了一遍dedian，现在已经成功启用了，
上次可能是由于系统的依赖和插件没安装全导致。

**Comment by xuexiyong** [comment]
代码为什么删了
想咨询，怎么让他每6个小时自动重新启动一下
dedian每次超过6个小时就没响应了！

**Comment by seatom** [comment]
暂时没时间去弄了，所以删了。定时可以在cron中设置， sudo vim /etc/crontab 最后一行添加29 * * * * root/home/xx/crysadm/run.sh  这个是每个小时29分重启,xx改为用户名

发自我的手机

**Comment by xuexiyong** [comment]
好的，知道了，谢谢解答！
顺便问下 程序不用先停止在运行吗？



2016-06-07 10:47 GMT+08:00 Seatom <notifications@github.com>:

**Comment by seatom** [comment]
run.sh执行的是先停止再启动



发自我的手机

**Comment by xuexiyong** [comment]
啊，对，脚本前两行是停止服务。
再次感谢！！

2016-06-07 11:09 GMT+08:00 Seatom <notifications@github.com>:

**Comment by ghost** [comment]
你好,咨询下,在那里能更新到crysadm 的 最新的代码
现在登陆又提示 安全问题了

2016-06-07 11:25 GMT+08:00 芥末雨粒 wakan.qi@gmail.com:

**Comment by seatom** [comment]
作者在这个QQ群里513786264

发自我的手机

**Comment by ghost** [comment]
好，知道了，谢谢~！！

2016-06-29 6:18 GMT+08:00 Seatom notifications@github.com:
